version: "3.9"

services:
  php:
    build: ./backend
    container_name: survivor_php
    working_dir: /var/www/html
    volumes:
      - ./backend:/var/www/html
      - ./frontend:/var/www/frontend
      - ./php/custom-www.conf:/usr/local/etc/php-fpm.d/www.conf
    depends_on:
      - db

  nginx:
    image: nginx:latest
    container_name: survivor_nginx
    ports:
      - "8000:80"
    volumes:
      - ./backend:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php

  db:
    image: postgres:17.4
    container_name: survivor_db
    environment:
      POSTGRES_DB: survivor
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
    ports:
      - "5432:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

  pgadmin:
    image: dpage/pgadmin4
    container_name: survivor_pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@local.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    depends_on:
      - db

volumes:
  postgres-data:
  pgadmin-data:
