<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20250419201536 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql(<<<'SQL'
            CREATE TABLE trait_def (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, key VARCHAR(100) NOT NULL, label VARCHAR(255) NOT NULL, description TEXT DEFAULT NULL, type VARCHAR(50) NOT NULL, PRIMARY KEY(id))
        SQL);
        $this->addSql(<<<'SQL'
            CREATE UNIQUE INDEX UNIQ_CBB068D18A90ABA9 ON trait_def (key)
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE player_trait ADD CONSTRAINT FK_1E76669F8C4FC8DF FOREIGN KEY (trait_def_id) REFERENCES trait_def (id) NOT DEFERRABLE INITIALLY IMMEDIATE
        SQL);
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql(<<<'SQL'
            DROP TABLE trait_def
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE player_trait DROP CONSTRAINT FK_1E76669F8C4FC8DF
        SQL);
    }
}
