<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20250420153804 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql(<<<'SQL'
            CREATE TABLE ai_log (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, model_name VARCHAR(255) NOT NULL, api_url VARCHAR(512) DEFAULT NULL, action_name VARCHAR(255) DEFAULT NULL, user_prompt TEXT DEFAULT NULL, system_prompt TEXT DEFAULT NULL, request_json TEXT DEFAULT NULL, response_json TEXT DEFAULT NULL, return_content TEXT DEFAULT NULL, duration INT DEFAULT NULL, PRIMARY KEY(id))
        SQL);
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql(<<<'SQL'
            DROP TABLE ai_log
        SQL);
    }
}
