<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20250902180204 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE ai_log (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, model_name VARCHAR(255) NOT NULL, api_url VARCHAR(512) DEFAULT NULL, action_name VARCHAR(255) DEFAULT NULL, user_prompt TEXT DEFAULT NULL, system_prompt TEXT DEFAULT NULL, request_json TEXT DEFAULT NULL, response_json TEXT DEFAULT NULL, return_content TEXT DEFAULT NULL, duration INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE app_user (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, email VARCHAR(180) NOT NULL, roles JSON NOT NULL, password VARCHAR(255) NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_88BDF3E9E7927C74 ON app_user (email)');
        $this->addSql('CREATE TABLE game (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, is_sandbox BOOLEAN NOT NULL, owner_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_232B318C7E3C61F9 ON game (owner_id)');
        $this->addSql('CREATE TABLE player (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(255) NOT NULL, is_user_controlled BOOLEAN NOT NULL, description TEXT DEFAULT NULL, game_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_98197A65E48FD905 ON player (game_id)');
        $this->addSql('CREATE TABLE player_trait (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, strength NUMERIC(3, 2) NOT NULL, player_id INT NOT NULL, trait_def_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_1E76669F99E6F5DF ON player_trait (player_id)');
        $this->addSql('CREATE INDEX IDX_1E76669F8C4FC8DF ON player_trait (trait_def_id)');
        $this->addSql('CREATE TABLE trait_def (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, key VARCHAR(100) NOT NULL, label VARCHAR(255) NOT NULL, description TEXT DEFAULT NULL, type VARCHAR(50) NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_CBB068D18A90ABA9 ON trait_def (key)');
        $this->addSql('ALTER TABLE game ADD CONSTRAINT FK_232B318C7E3C61F9 FOREIGN KEY (owner_id) REFERENCES app_user (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE player ADD CONSTRAINT FK_98197A65E48FD905 FOREIGN KEY (game_id) REFERENCES game (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE player_trait ADD CONSTRAINT FK_1E76669F99E6F5DF FOREIGN KEY (player_id) REFERENCES player (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE player_trait ADD CONSTRAINT FK_1E76669F8C4FC8DF FOREIGN KEY (trait_def_id) REFERENCES trait_def (id) NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE game DROP CONSTRAINT FK_232B318C7E3C61F9');
        $this->addSql('ALTER TABLE player DROP CONSTRAINT FK_98197A65E48FD905');
        $this->addSql('ALTER TABLE player_trait DROP CONSTRAINT FK_1E76669F99E6F5DF');
        $this->addSql('ALTER TABLE player_trait DROP CONSTRAINT FK_1E76669F8C4FC8DF');
        $this->addSql('DROP TABLE ai_log');
        $this->addSql('DROP TABLE app_user');
        $this->addSql('DROP TABLE game');
        $this->addSql('DROP TABLE player');
        $this->addSql('DROP TABLE player_trait');
        $this->addSql('DROP TABLE trait_def');
    }
}
