<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20250419190838 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql(<<<'SQL'
            CREATE TABLE game (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, is_sandbox BOOLEAN NOT NULL, PRIMARY KEY(id))
        SQL);
        $this->addSql(<<<'SQL'
            CREATE TABLE player (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(255) NOT NULL, is_user_controlled BOOLEAN NOT NULL, description TEXT DEFAULT NULL, game_id INT NOT NULL, PRIMARY KEY(id))
        SQL);
        $this->addSql(<<<'SQL'
            CREATE INDEX IDX_98197A65E48FD905 ON player (game_id)
        SQL);
        $this->addSql(<<<'SQL'
            CREATE TABLE player_trait (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, strength NUMERIC(3, 2) NOT NULL, player_id INT NOT NULL, trait_def_id INT NOT NULL, PRIMARY KEY(id))
        SQL);
        $this->addSql(<<<'SQL'
            CREATE INDEX IDX_1E76669F99E6F5DF ON player_trait (player_id)
        SQL);
        $this->addSql(<<<'SQL'
            CREATE INDEX IDX_1E76669F8C4FC8DF ON player_trait (trait_def_id)
        SQL);
        $this->addSql(<<<'SQL'
            CREATE TABLE trait_def (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, key VARCHAR(100) NOT NULL, label VARCHAR(255) NOT NULL, description TEXT DEFAULT NULL, type VARCHAR(50) NOT NULL, PRIMARY KEY(id))
        SQL);
        $this->addSql(<<<'SQL'
            CREATE UNIQUE INDEX UNIQ_CBB068D18A90ABA9 ON trait_def (key)
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE player ADD CONSTRAINT FK_98197A65E48FD905 FOREIGN KEY (game_id) REFERENCES game (id) NOT DEFERRABLE INITIALLY IMMEDIATE
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE player_trait ADD CONSTRAINT FK_1E76669F99E6F5DF FOREIGN KEY (player_id) REFERENCES player (id) NOT DEFERRABLE INITIALLY IMMEDIATE
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE player_trait ADD CONSTRAINT FK_1E76669F8C4FC8DF FOREIGN KEY (trait_def_id) REFERENCES trait_def (id) NOT DEFERRABLE INITIALLY IMMEDIATE
        SQL);
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql(<<<'SQL'
            ALTER TABLE player DROP CONSTRAINT FK_98197A65E48FD905
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE player_trait DROP CONSTRAINT FK_1E76669F99E6F5DF
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE player_trait DROP CONSTRAINT FK_1E76669F8C4FC8DF
        SQL);
        $this->addSql(<<<'SQL'
            DROP TABLE game
        SQL);
        $this->addSql(<<<'SQL'
            DROP TABLE player
        SQL);
        $this->addSql(<<<'SQL'
            DROP TABLE player_trait
        SQL);
        $this->addSql(<<<'SQL'
            DROP TABLE trait_def
        SQL);
    }
}
